---
version: "2.1"
services:
  nextcloud:
    image: ghcr.io/linuxserver/nextcloud
    container_name: nextcloud
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /home/yuu/Documents/Applications/Nextcloud/config:/config
      - /home/yuu/Documents/Applications/Nextcloud/data:/data
    ports:
      - 443:443
    restart: unless-stopped
