version: ""
services:
  jackett:
    image: ghcr.io/linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - AUTO_UPDATE=true
    volumes:
      - /home/yuu/Documents/Applications/Jackett/Config:/config
      - /home/yuu/Documents/Applications/Jackett/Blackhole:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped
