version: ""
services:
    tor:
        image: jess/tor-proxy
        container_name: tor-proxy
        ports:
            - 9050:9050
        networks:
            - tor-privoxy
        restart: unless-stopped
            
    privoxy:
        image: jess/privoxy
        container_name: privoxy
        ports:
            - 8118:8118
        networks:
            - tor-privoxy
        restart: unless-stopped

networks:
    tor-privoxy:
