# docker container run \
#   --name gallery-dl \
#   -it \
#   -v C:\Users\username\Youtube-dl:/youtube-dl (Windows)
#   -v /home/username/Youtube-dl:/youtube-dl (Linux)
#   alpine

FROM alpine
ENV ALPINE_FRONTEND=noninteractive
RUN apk update
RUN apk add youtube-dl
WORKDIR /youtube-dl
